---
title: "Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file = "../Code/my_rf_cv.R")
```

```{r my_rf_cv}
library(dplyr)
library(randomForest)
library(ggplot2)
my_penguins <- read.csv("../Data/my_penguins.csv")
# run functions for 30 times with k = 2, 5, 10.
cv_2 <- replicate(30, my_rf_cv(2))
cv_5 <- replicate(30, my_rf_cv(5))
cv_10 <- replicate(30, my_rf_cv(10))
# Store results as a data frame
cv_df <- data.frame("k_2" = cv_2,
                    "k_5" = cv_5,
                    "k_10" = cv_10)
# Plot the results as a boxplot
cv_plot_df <- data.frame("k" = c(rep(2,30),rep(5,30), rep(10,30)),
                 "cv" = c(cv_2,cv_5,cv_10))
cv_plot <- ggplot(cv_plot_df, aes(factor(k), cv)) +
  geom_boxplot() +
  labs(x = c("k"), y = c("CV estimated MSE"))
cv_plot
# Display table with 
cv_table <- data.frame("k" = c(2, 5, 10),
                       "Mean" = c(mean(cv_2),mean(cv_5),mean(cv_10)),
                       "Standard Deviation" = c(sd(cv_2),sd(cv_5),sd(cv_10)))
cv_table
ggsave("cv_plot", cv_plot, device = "png", path = "../Output/Figures")
write.csv(cv_df, "../Output/Results/Simulations.csv")
saveRDS(cv_table, "../Output/Results/summary_statistics")
                       
```
